<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: sqlite3
  database: log/development.sqlite3
  
test:
  adapter: sqlite3
  database: log/test.sqlite3
  
staging:
  adapter: mysql
  database: odyssey_staging
  username: odyssey
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
  
production:
  adapter: mysql
  database: odyssey_production
  username: odyssey
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST